application: journey-to-the-moon
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /cities.json
  static_files: static/cities.json
  upload: static/cities.json
  expiration: 100d

- url: /(.*\.(html|css|js|eot|svg|ttf|woff|ico))
  static_files: static/\1
  upload: static/(.*\.(html|css|js|eot|svg|ttf|woff|ico))

- url: /(.*\.png)
  static_files: static/\1
  upload: static/(.*\.png)
  mime_type: image/png

- url: /(.*\.jpg)
  static_files: static/\1
  upload: static/(.*\.jpg)
  mime_type: image/jpeg

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest