application: journey-to-the-moon
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /cities.json
  static_files: static/cities.json
  upload: static/cities.json
  expiration: 100d

- url: /(.*\.(html|css|js|eot|svg|ttf|woff))
  static_files: static/\1
  upload: static/(.*\.(html|css|js|eot|svg|ttf|woff))

- url: /(.*\.png)
  static_files: static/\1
  upload: static/(.*\.png)
  mime_type: image/png

- url: /
  static_files: static/index.html
  upload: static/index.html
